### ISSUE TITLE
Load Entities from RON

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/amethyst#112]
We should be able to construct entities from YAML files (*.yml) stored in the `resources/entities` directory. Files can be nested arbitrarily in subfolders for organizational purposes, if the user wants. The markup format should be as follows:

``` yaml

---
component1:
    field1: true
    field2: 'value'
    field3: [1.0, 2.1]

component2:
    field1:
        - thing1
        - thing2
        - thing3
```

The string name of the entity is the filename minus the `.yml` extension. The user should be able to create an instance of such an entity in Rust code.

**Comment by msiglreith** [comment]
Remark: Relevant specs issues https://github.com/slide-rs/specs/issues/18

**Comment by mechaxl** [comment]
After taking a look at the ability to load a world/map in #145, I'm wondering how this will work for that use case. Using this approach for loading individual entities seems fine, but I think doesn't address the overall question of how to load a game world. It seems like we can proxy off most/all of the "real work" to `specs-rs`, so if this looks right from Amethyst's POV, I can go propose this over there to see if there's any interest. Basically, it would look something like this:

```rust
impl State for SomeExample {
    fn on_start(&mut self, ctx: &mut Context, world: &mut World) {
        world.register_component(Component1, "component1");
        world.register_component(Component2, "component2");
        
        world.load("example");
    }
}
```

With a `resources/worlds/example.yml` file that looks like this:

```yaml
---
entities:
  - component1:
      field1: true
      field2: 'value'
      field3: [1.0, 2.1]

  - component1:
      field1: false
      field2: 'value'
      field3: [1.0, 2.1]
    component2:
      field1: []
```
