### ISSUE TITLE
Load Prefabs from RON

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/amethyst#122]
We should be able to construct prefabs from YAML files (*.yml) stored in the `resources/prefabs` directory. Files can be nested arbitrarily in subfolders for organizational purposes, if the user wants. The markup format should be identical to that of [entities](https://github.com/amethyst/amethyst/issues/112):

``` yaml

---
component1:
    field1: true
    field2: 'value'
    field3: [1.0, 2.1]

component2:
    field1:
        - thing1
        - thing2
        - thing3
```

The string name of the prefab is the filename minus the `.yml` extension. The user should be able to create entities deriving from such prefabs in Rust code. However, this should also be doable from within YAML as well, following the format below:

``` yaml
extends: name_of_prefab

---
component3:
    field1: [0.1, 2.6]
```
