### ISSUE TITLE
[BUG] Amethyst_test crate not avaialble

### ISSUE THREAD

**Issue by fredlangva** [amethyst/amethyst#1427]
## Description

Cargo can't find amethyst_test

## Reproduction Steps
extern crate amethyst_test;

use amethyst_test::prelude::*;

error[E0463]: can't find crate for `amethyst_test`
 --> src\main.rs:2:1
  |
2 | extern crate amethyst_test;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

**Comment by torkleyy** [comment]
@azriel91 I think we never published `amethyst_test`, did we?

**Comment by azriel91** [comment]
Looks like we haven't; currently we have to do this:

```toml
[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
```

Let's make sure it's published when we do 0.11

**Comment by azriel91** [comment]
And it's up!

* crates.io: https://crates.io/crates/amethyst_test
* Handy dandy toml:

    ```toml
    [dev-dependencies]
    amethyst_test = "0.1.0"
    ```

Note: this is for amethyst 0.10.0. In 0.11.0 `amethyst_test` will have a breaking change.
