### ISSUE TITLE
amethyst as dependency fails on apple m1 chip

### ISSUE THREAD

**Issue by InterruptSpeed** [amethyst/amethyst#2671]
## Description

cargo build fails due to error[E0308]: mismatched types b/c it is targeting winit 19.5. as of Nov 2020 this issue with winit is fixed [rust-windowing/winit#1782](https://github.com/rust-windowing/winit/issues/1782)

## Reproduction Steps

1. cargo new pong
2. cd pong
3. amethyst = "0.15.3" as dependency
4. cargo build

## What You Expected to Happen

a clean build

## Screenshots and Logs

```
error[E0308]: mismatched types

window.setFrame_display_(current_rect, 0)
     |                                                ^ expected `bool`, found integer
error: aborting due to 7 previous errors
```

## Your Environment

Operating System: macOS Big Sur
Operating System Version: 11.2.3
Version of Amethyst: 0.15.3

**Comment by Marcus-Rise** [comment]
same issue, can't compile with this lib on my mb pro with m1 chip
[amethyst-starter-2d](https://github.com/amethyst/amethyst-starter-2d) is not building

**Comment by Marcus-Rise** [comment]
@InterruptSpeed, can you try use git link to package in `Cargo.toml`?

```toml
[dependencies]
amethyst = {git = "https://github.com/amethyst/amethyst", branch="main", features = ["no-slow-safety-checks"]}
```
